### ISSUE TITLE
Update for SimpleOpenNI 0.27.0

### ISSUE THREAD

**Issue by chazmatazz** [aperiodic/bifocals#2]
Please update for SimpleOpenNI 0.27.0

**Comment by aperiodic** [comment]
Are there specific features in this release you'd like to see supported, or do you just want the updated middleware?

**Comment by chazmatazz** [comment]
We need Linux32 support. I think this is the first release that supports Linux32.

**Comment by aperiodic** [comment]
Have you tried the current version? It contains libSimpleOpenNI.so for x86/i386 architectures (in addition to libSimpleOpenNI64.so for x86_64/amd64), so it seems like it should work on 32-bit Linux.

**Comment by chazmatazz** [comment]
We didn't try 0.26, we only tried 0.27

On Sun, Jun 3, 2012 at 3:55 AM, Dan Lidral-Porter <
reply@reply.github.com

> wrote:
> 
> Have you tried the current version? It contains libSimpleOpenNI.so for
> x86/i386 architectures (in addition to libSimpleOpenNI64.so for
> x86_64/amd64), so it seems like it should work on 32-bit Linux.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/aperiodic/bifocals/issues/2#issuecomment-6084287

## 

Charles

**Comment by aperiodic** [comment]
Ok, I think 0.26 would work fine for you, but I've updated the simple-open-ni dep regardless, and made a new release.
