### ISSUE TITLE
Interested in the current state of this project

### ISSUE THREAD

**Issue by worace** [aperiodic/bifocals#4]
Hi there -

I came across this project today while I was looking around for ways to access a Kinect with Clojure. I'd be very interested in using it but have been having trouble getting it running. I understand it's been a few years since you wrote it so I'm wondering if there may have been some configuration or dependency updates in the meantime that I'm not be accounting for.

A couple things I've tried:
- Cloning bifocals and running the repl in that project -- getting lots of "Unable to resolve symbol" [errors from the compiler](https://gist.github.com/worace/3eef65c2d48ee51675ff#file-trying_to_run_bifocals_repl)
- Cloning an example bifocals repo ([https://github.com/mudphone/zoestory](https://github.com/mudphone/zoestory)) and running the repl there -- getting similar symbol errors (https://gist.github.com/worace/3eef65c2d48ee51675ff#file-running_zoestory_repl-txt)
- Using `lein run` in that same repl -- this time getting errors about [a native library libOpenNI.dylib](https://gist.github.com/worace/3eef65c2d48ee51675ff#file-running_zoestory-core-txt)

I think the latter of these issues may have to do with updates in the processing library libSimpleOpenNI -- I think they're now using `libOpenNI2.dylib` instead. For what it's worth I've been able to run some sample Processing Sketches using libSimpleOpenNI straight from processing, but would like to be able to figure out a way to use it from quil instead.

As for all the build issues I'm somewhat at a loss. Still pretty new to clojure so very possible I'm just doing something stupid.

Anyway sorry to drop this on you out of the blue, but if there's any chance you've run into issues like these or are aware of any problems around libSimpleOpenNI upgrades, I'd love to chat about them.

**Comment by szymonkaliski** [comment]
Hey @worace I'm in the same situation, did you manage to solve it somehow? If not — @aperiodic — could you maybe comment on those issues? :)
